name: "Renovate Config Validation"

on:
  push:
    branches:
      - master
    paths:
      - renovate.json
      - renovate/**
  pull_request:
    branches:
      - master
    paths:
      - renovate.json
      - renovate/**

jobs:
  renovate-config-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
      - run: npx --yes --package renovate -- renovate-config-validator --strict renovate.json renovate/*.json
